import React,{useState} from 'react';
import {Plus,Search,Pencil,Trash2,Package,Loader2,X,Save,UploadCloud,Download} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {api,errorText,units,exportItemsCSV} from '@/components/plant/plantUtils';
import MasterImportDialog from '@/components/plant/MasterImportDialog';
import {useToast} from '@/components/ui/use-toast';
export default function ItemMasterPage({workspace,items,onSaved}) {
  const [search,setSearch]=useState(''),[edit,setEdit]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const [importOpen,setImportOpen]=useState(false);
  const [selected,setSelected]=useState(new Set());
  const [confirmAll,setConfirmAll]=useState(false);
  const [sort,setSort]=useState({key:'code',dir:'asc'});
  const {toast}=useToast();
  const filtered0=items.filter(i=>!search||i.code?.toLowerCase().includes(search.toLowerCase())||i.description?.toLowerCase().includes(search.toLowerCase()));
  const sv=(i,k)=>k==='stock'?(Number(i.stock)||0):String(i[k]||'').toLowerCase();
  const filtered=[...filtered0].sort((a,b)=>{const av=sv(a,sort.key),bv=sv(b,sort.key);const cmp=av<bv?-1:av>bv?1:0;return sort.dir==='asc'?cmp:-cmp;});
  const openNew=()=>setEdit({code:'',description:'',bin_location:'',stock:0,unit:'',category:''});
  const save=async e=>{e.preventDefault();setBusy(true);setError('');try{const updating=Boolean(edit.id);await api('saveItem',{workspace_id:workspace.id,id:edit.id,data:edit});await onSaved();setEdit(null);toast({title:updating?'Item updated':'Item added'});}catch(e){const msg=errorText(e);setError(msg);toast({title:'Save failed',description:msg,variant:'destructive'});}finally{setBusy(false);}};
  const remove=async id=>{if(!confirm('Delete this item?'))return;setBusy(true);setError('');try{await api('deleteItem',{workspace_id:workspace.id,id});await onSaved();toast({title:'Item deleted'});}catch(e){const msg=errorText(e);setError(msg);toast({title:'Delete failed',description:msg,variant:'destructive'});}finally{setBusy(false);}};
  const toggle=id=>setSelected(p=>{const n=new Set(p);n.has(id)?n.delete(id):n.add(id);return n;});
  const allSelected=filtered.length>0&&filtered.every(i=>selected.has(i.id));
  const toggleAll=()=>{const ids=filtered.map(i=>i.id);if(ids.every(id=>selected.has(id)))setSelected(new Set([...selected].filter(id=>!ids.includes(id))));else setSelected(new Set([...selected,...ids]));};
  const deleteSelected=async()=>{if(!selected.size)return;if(!confirm(`Delete ${selected.size} selected item${selected.size!==1?'s':''}?`))return;setBusy(true);setError('');try{await api('massDeleteItems',{workspace_id:workspace.id,ids:[...selected]});setSelected(new Set());await onSaved();toast({title:'Items deleted'});}catch(e){const msg=errorText(e);setError(msg);toast({title:'Delete failed',description:msg,variant:'destructive'});}finally{setBusy(false);}};
  const deleteAll=async()=>{if(!confirm('Delete ALL items in this workspace? This cannot be undone.'))return;setBusy(true);setError('');try{await api('deleteAllItems',{workspace_id:workspace.id});setSelected(new Set());setConfirmAll(false);await onSaved();toast({title:'All items deleted'});}catch(e){const msg=errorText(e);setError(msg);toast({title:'Delete failed',description:msg,variant:'destructive'});}finally{setBusy(false);}};
  const set=(k,v)=>setEdit(p=>({...p,[k]:v}));
  const stockBadge=s=>s>0?<span className="stock-badge in">{s} in stock</span>:<span className="stock-badge out">Out of stock</span>;
  return <><div className="page-header"><div><h1>Item Master</h1><p>Spare parts and material code registry. Auto-fills descriptions in work order forms.</p></div><div className="page-actions"><button className="secondary-button" onClick={()=>{const n=exportItemsCSV(filtered);toast(n?{title:'Item master exported',description:`${n} item${n===1?'':'s'} downloaded.`}:{title:'Nothing to export',description:'No items match the current search.',variant:'destructive'});}} disabled={!filtered.length}><Download size={16}/>Export CSV</button><button className="secondary-button" onClick={()=>setImportOpen(true)}><UploadCloud size={16}/>Import CSV</button><button className="danger-button" onClick={()=>setConfirmAll(true)} disabled={!items.length||busy}><Trash2 size={16}/>Delete All</button><button className="primary-button" onClick={openNew}><Plus size={16}/>Add item</button></div></div>
    <div className="master-toolbar"><label className="master-search"><Search size={16}/><input placeholder="Search by code or description..." value={search} onChange={e=>setSearch(e.target.value)}/></label><span className="count-badge">{filtered.length} items</span>{selected.size>0&&<><span style={{fontSize:13,fontWeight:600}}>{selected.size} selected</span><button className="danger-button" onClick={deleteSelected} disabled={busy}><Trash2 size={14}/>Delete Selected</button><button className="secondary-button" onClick={()=>setSelected(new Set())}><X size={14}/>Clear</button></>}</div>
    <section className="panel order-panel"><div className="table-scroll"><table className="master-table"><thead><tr><th className="check-col"><input type="checkbox" className="header-checkbox" checked={allSelected} onChange={toggleAll} aria-label="Select all"/></th>{[['code','ITEM CODE'],['description','DESCRIPTION'],['bin_location','BIN LOCATION'],['stock','STOCK'],['unit','UNIT'],['category','CATEGORY']].map(([k,l])=><th key={k}><button onClick={()=>setSort(p=>p.key===k?{key:k,dir:p.dir==='asc'?'desc':'asc'}:{key:k,dir:'asc'})} style={{display:'inline-flex',alignItems:'center',gap:3,background:'none',border:'none',color:'inherit',fontSize:'10px',letterSpacing:'.5px',fontWeight:700,cursor:'pointer',padding:0}}>{l}{sort.key===k?(sort.dir==='asc'?'▲':'▼'):'↕'}</button></th>)}<th></th></tr></thead><tbody>{filtered.map(i=><tr key={i.id} className={selected.has(i.id)?'selected':''}><td className="check-col"><input type="checkbox" className="row-checkbox" checked={selected.has(i.id)} onChange={()=>toggle(i.id)} aria-label={`Select ${i.code}`}/></td><td><strong style={{fontFamily:'monospace'}}>{i.code}</strong></td><td>{i.description}</td><td>{i.bin_location||'—'}</td><td>{stockBadge(i.stock||0)}</td><td>{i.unit||'—'}</td><td>{i.category||'—'}</td><td><div className="master-actions"><button onClick={()=>setEdit(i)}><Pencil size={14}/></button><button className="danger" onClick={()=>remove(i.id)}><Trash2 size={14}/></button></div></td></tr>)}</tbody></table>{!filtered.length&&<div className="master-empty"><Package size={28}/><h3>No items in registry</h3><p>Add spare parts and materials to enable auto-fill in work order material lines.</p></div>}</div></section>
    {error&&<div className="content-error"><X size={16}/>{error}</div>}
    {confirmAll&&<Dialog open onOpenChange={()=>setConfirmAll(false)}><DialogContent className="master-dialog"><DialogTitle>Delete All Items?</DialogTitle><DialogDescription>This will permanently remove every item in this workspace registry.</DialogDescription><div className="flex gap-2 justify-end mt-4"><button className="secondary-button" onClick={()=>setConfirmAll(false)} disabled={busy}>Cancel</button><button className="danger-button" onClick={deleteAll} disabled={busy}>{busy?<Loader2 size={16} className="animate-spin"/>:<Trash2 size={16}/>}Delete All</button></div></DialogContent></Dialog>}
    {edit&&<Dialog open onOpenChange={v=>!v&&!busy&&setEdit(null)}><DialogContent className="master-dialog"><DialogTitle>{edit.id?'Edit Item':'Add Item'}</DialogTitle><DialogDescription>Item codes auto-fill descriptions in work order material lines.</DialogDescription>
      <form onSubmit={save}><div className="form-grid"><label className="form-field">Item Code<input required value={edit.code} onChange={e=>set('code',e.target.value)}/></label><label className="form-field">Unit<select value={edit.unit||''} onChange={e=>set('unit',e.target.value)}><option value="">—</option>{units.map(u=><option key={u}>{u}</option>)}</select></label></div>
      <label className="form-field mt-4">Description<input required value={edit.description} onChange={e=>set('description',e.target.value)}/></label>
      <div className="form-grid mt-4"><label className="form-field">Bin Location<input placeholder="e.g., A-12-03" value={edit.bin_location} onChange={e=>set('bin_location',e.target.value)}/></label><label className="form-field">Stock Quantity<input type="number" min="0" step="any" value={edit.stock} onChange={e=>set('stock',Number(e.target.value))}/></label></div>
      <label className="form-field mt-4">Category<input placeholder="e.g., Valves, Instruments" value={edit.category} onChange={e=>set('category',e.target.value)}/></label>
      {error&&<p className="form-error" role="alert">{error}</p>}
      <div className="flex gap-2 mt-4 justify-end"><button type="button" className="secondary-button" disabled={busy} onClick={()=>setEdit(null)}>Cancel</button><button type="submit" className="primary-button" disabled={busy}>{busy?<Loader2 size={16} className="animate-spin"/>:<Save size={16}/>} Save item</button></div>
      </form>
    </DialogContent></Dialog>}
    {importOpen&&<MasterImportDialog workspace={workspace} action="importItems" onClose={()=>setImportOpen(false)} onSaved={onSaved}/>}
  </>;
}