import React,{useState} from 'react';
import {Save,Trash2,ClipboardList,Loader2,Pencil} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import JobFields from '@/components/plant/JobFields';
import MaterialEditor from '@/components/plant/MaterialEditor';
import ConfirmDelete from '@/components/plant/ConfirmDelete';
import {api,errorText,safeFormatDate,priorityLabel} from '@/components/plant/plantUtils';
import { useToast } from '@/components/ui/use-toast';
const RO=({label,value})=><div className="read-only-field"><label>{label}</label><span>{value||<span className="muted">Not specified</span>}</span></div>;
const fmtDate=v=>safeFormatDate(v,'dd MMM yyyy')||'—';
const fmtDT=v=>safeFormatDate(v,'dd MMM yyyy HH:mm')||'—';
export default function OrderDrawer({job,workspace,admin,systems,onClose,onSaved}) {
  const [value,setValue]=useState({technician:'',ptw_number:'',deferred_reason:'',pr_number:'',action_taken:'',as_found:'',as_left:'',materials:[],maintenance_type:'CM',pm_frequency:'',shutdown_item:false,associated_wo:'',...job}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[confirm,setConfirm]=useState(false);
  const {toast}=useToast();
  const [readOnly,setReadOnly]=useState(!!job.id);
  const set=(k,v)=>setValue(p=>({...p,[k]:v}));
  const restricted=!admin&&job.id&&job.job_type!=='Break-In';
  const normalize=v=>({wo_number:String(v.wo_number||''),description:String(v.description||''),equipment_tag:String(v.equipment_tag||''),system:String(v.system||''),unit:v.unit||'',priority:v.priority||'',job_type:v.job_type||'',maintenance_type:v.maintenance_type||'CM',pm_frequency:v.pm_frequency||'',shutdown_item:!!v.shutdown_item,status:v.status||'Open',technician:String(v.technician||''),planned_start:String(v.planned_start||''),planned_finish:String(v.planned_finish||''),start_time:String(v.start_time||''),completion_time:String(v.completion_time||''),action_taken:String(v.action_taken||''),as_found:String(v.as_found||''),as_left:String(v.as_left||''),ptw_number:String(v.ptw_number||''),associated_wo:String(v.associated_wo||''),deferred_reason:v.deferred_reason||'',pr_number:String(v.pr_number||''),materials:Array.isArray(v.materials)?v.materials:[]});
  const save=async e=>{e.preventDefault();setBusy(true);setError('');try{await api('save',{workspace_id:workspace.id,id:job.id,data:normalize(value)});await onSaved();onClose();}catch(e){const msg=errorText(e);setError(msg);toast({title:'Save failed',description:msg,variant:'destructive'});}finally{setBusy(false);}};
  const remove=async()=>{setBusy(true);setError('');try{await api('delete',{workspace_id:workspace.id,id:job.id});await onSaved();onClose();}catch(e){const msg=errorText(e);setError(msg);toast({title:'Delete failed',description:msg,variant:'destructive'});setConfirm(false);}finally{setBusy(false);}};
  return <><Dialog open onOpenChange={v=>!v&&!busy&&onClose()}><DialogContent className="order-drawer" onInteractOutside={e=>e.preventDefault()}>
    <div className="drawer-heading"><span className="drawer-icon"><ClipboardList size={21}/></span><div><DialogTitle style={{display:'flex',alignItems:'center',gap:8}}>{job.id?job.wo_number:job.job_type==='Break-In'?'New emergency / break-in job':'New work order'}{job.ex_breakin&&<span className="ex-breakin-pill">⚡ Ex-BreakIn</span>}</DialogTitle><DialogDescription>{job.id?(readOnly?'Review the complete work record.':'Inspect and update the complete work record.'):'Capture the job. Keep your shift moving.'}</DialogDescription></div></div>
    {readOnly&&job.id?<><div className="drawer-scroll">
      <div className="read-only-section"><h3>Job Information</h3><div className="read-only-grid"><RO label="WO Number" value={value.wo_number}/><RO label="Job Type" value={value.job_type}/><RO label="Unit" value={value.unit}/><RO label="System" value={value.system}/><RO label="Priority" value={priorityLabel(value)}/><RO label="Equipment Tag" value={value.equipment_tag}/><RO label="Planned Start" value={fmtDate(value.planned_start)}/><RO label="Planned Finish" value={fmtDate(value.planned_finish)}/></div><div className="read-only-field" style={{gridColumn:'1/-1'}}><label>Description</label><span>{value.description}</span></div></div>
      <div className="read-only-section"><h3>Execution Details</h3><div className="read-only-grid"><RO label="Assigned Manpower" value={value.technician?.trim()||'Unassigned'}/><RO label="Actual Start" value={fmtDT(value.start_time)}/><RO label="Completion Time" value={fmtDT(value.completion_time)}/><RO label="PTW Number" value={value.ptw_number}/><RO label="Deferred Reason" value={value.deferred_reason}/><RO label="PR Number" value={value.pr_number}/><RO label="Maintenance Type" value={value.maintenance_type||'CM'}/>{value.maintenance_type==='PM'&&<RO label="PM Frequency" value={value.pm_frequency||'—'}/>}{value.job_type==='Break-In'&&<RO label="Associated WO #" value={value.associated_wo}/>}</div></div>
      <div className="read-only-section"><h3>Execution Log</h3><RO label="Action Taken" value={value.action_taken||'N/A - Pending Details'}/><RO label="As-Found Condition" value={value.as_found||'N/A - Pending Details'}/><RO label="As-Left Condition" value={value.as_left||'N/A - Pending Details'}/><RO label="Status" value={value.status}/></div>
      {value.materials?.length>0&&<div className="read-only-section"><h3>Materials Consumed</h3><div className="material-list-ro">{value.materials.map((m,i)=><div key={i}><strong>{m.code}</strong><span>{m.description}</span><small>Qty: {m.quantity}</small></div>)}</div></div>}
      {error&&<p role="alert" className="form-error">{error}</p>}
    </div><div className="drawer-footer">{admin&&(!restricted)&&<button type="button" className="delete-link" onClick={()=>setConfirm(true)} disabled={busy}><Trash2 size={16}/>Delete</button>}<div className="flex gap-2 ml-auto"><button type="button" className="secondary-button" disabled={busy} onClick={onClose}>Close</button>{(!restricted||admin)&&<button type="button" className="primary-button" onClick={()=>setReadOnly(false)}><Pencil size={16}/>Edit Work Order</button>}</div></div></>:<>
    <form onSubmit={save} className="drawer-form"><div className="drawer-scroll"><JobFields value={value} set={set} restricted={restricted} systems={systems}/><MaterialEditor value={value.materials} onChange={v=>set('materials',v)} workspace={workspace}/>{error&&<p role="alert" className="form-error">{error}</p>}</div><div className="drawer-footer">{job.id&&(!restricted)&&<button type="button" className="delete-link" onClick={()=>setConfirm(true)} disabled={busy}><Trash2 size={16}/>Delete</button>}<div className="flex gap-2 ml-auto"><button type="button" className="secondary-button" disabled={busy} onClick={onClose}>Cancel</button><button type="submit" className="primary-button" disabled={busy}>{busy?<Loader2 size={16} className="animate-spin"/>:<Save size={16}/>} {busy?'Saving…':'Save work order'}</button></div></div></form></>}
  </DialogContent></Dialog><ConfirmDelete open={confirm} onClose={()=>setConfirm(false)} onConfirm={remove} busy={busy}/></>;
}