import React,{useState} from 'react';
import {format,startOfMonth,endOfMonth,startOfWeek,endOfWeek,eachDayOfInterval,addMonths,addWeeks,isSameMonth} from 'date-fns';
import {ChevronLeft,ChevronRight} from 'lucide-react';
import {today,aged} from '@/components/plant/plantUtils';
export default function WorkCalendar({orders,onDateSelect,pmMode=false}) {
  const [anchor,setAnchor]=useState(new Date()),[view,setView]=useState('Month');
  const start=startOfWeek(view==='Month'?startOfMonth(anchor):anchor,{weekStartsOn:0}),end=endOfWeek(view==='Month'?endOfMonth(anchor):anchor,{weekStartsOn:0});
  const days=eachDayOfInterval({start,end});
  const move=n=>setAnchor(view==='Month'?addMonths(anchor,n):addWeeks(anchor,n));
  const monthOrders=orders.filter(j=>{const d=j.planned_start||j.completion_time?.slice(0,10);if(!d)return false;const dt=new Date(d+'T12:00:00');return dt>=startOfMonth(anchor)&&dt<=endOfMonth(anchor);});
  const stats=pmMode?[{label:'Total PM',count:monthOrders.length},{label:'Completed',count:monthOrders.filter(j=>j.status==='Completed').length},{label:'Open',count:monthOrders.filter(j=>j.status==='Open').length},{label:'Aged',count:monthOrders.filter(j=>aged(j)>0).length}]:[{label:'Planned',count:monthOrders.length},{label:'Completed',count:monthOrders.filter(j=>j.status==='Completed').length},{label:'Break-Ins',count:monthOrders.filter(j=>j.job_type==='Break-In').length},{label:'Aged',count:monthOrders.filter(j=>aged(j)>0).length}];
  return <section className="panel calendar-panel"><div className="calendar-header"><div><h3>{format(anchor,'MMMM yyyy')}</h3><p>{pmMode?'Click any date to add or reschedule a PM job':'Click any date to add, reschedule, or generate a report'}</p></div><div className="calendar-controls"><div className="segmented">{['Month','Week'].map(v=><button className={view===v?'active':''} key={v} onClick={()=>setView(v)}>{v}</button>)}</div><button className="secondary-button" onClick={()=>setAnchor(new Date())}>Today</button><button className="icon-button" aria-label="Previous calendar period" onClick={()=>move(-1)}><ChevronLeft size={17}/></button><button className="icon-button" aria-label="Next calendar period" onClick={()=>move(1)}><ChevronRight size={17}/></button></div></div>
  <div className="calendar-analytics">{stats.map(s=><div className="cal-stat" key={s.label}><strong>{s.count}</strong><span>{s.label}</span></div>)}</div>
  <div className="calendar-scroll"><div className="calendar-weekdays">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d=><span key={d}>{d}</span>)}</div><div className="calendar-grid">{days.map(d=>{const date=format(d,'yyyy-MM-dd');const dayJobs=orders.filter(j=>j.planned_start===date||(j.status==='Completed'&&j.completion_time?.slice(0,10)===date));const pm=dayJobs.filter(j=>j.maintenance_type==='PM').length;const scheduled=dayJobs.filter(j=>j.job_type!=='Break-In'&&j.maintenance_type!=='PM').length;const breakIns=dayJobs.filter(j=>j.job_type==='Break-In').length;const completed=dayJobs.filter(j=>j.status==='Completed').length;const deferred=dayJobs.filter(j=>j.status==='Deferred').length;return <div className={`calendar-day ${!isSameMonth(d,anchor)?'outside':''}`} key={date} onClick={()=>onDateSelect(date)} style={{cursor:'pointer'}}><span className={date===today()?'date-today':''}>{format(d,'d')}</span>{pmMode?<div className="calendar-day-body">{dayJobs.slice(0,3).map(j=><button key={j.id} className="calendar-job pm full-text" onClick={e=>{e.stopPropagation();onDateSelect(date);}}><strong>{j.wo_number}</strong><span>{j.description}</span><small>{j.pm_frequency||'PM'}</small></button>)}{dayJobs.length>3&&<button className="calendar-more" onClick={e=>{e.stopPropagation();onDateSelect(date);}}>+{dayJobs.length-3} more</button>}</div>:<div className="calendar-counts">{pm>0&&<div className="calendar-count-row pm">PM<span>{pm}</span></div>}{scheduled>0&&<div className="calendar-count-row scheduled">CM<span>{scheduled}</span></div>}{breakIns>0&&<div className="calendar-count-row breakin">Break-Ins<span>{breakIns}</span></div>}{completed>0&&<div className="calendar-count-row completed">Completed<span>{completed}</span></div>}{deferred>0&&<div className="calendar-count-row deferred">Deferred<span>{deferred}</span></div>}</div>}</div>;})}</div></div>
  <div className="calendar-legend">{pmMode?<><span><i style={{background:'#9333ea'}}/>PM job</span><span><i className="green-dot"/>Completed</span></>:<><span><i style={{background:'#9333ea'}}/>PM</span><span><i/>CM</span><span><i className="green-dot"/>Completed</span><span><i className="amber-dot"/>Break-in</span></>}</div></section>;
}