import React,{useState} from 'react';
import {Building2,ShieldCheck,Users,Save,Plus,X,Check,AlertTriangle,Trash2,Loader2} from 'lucide-react';
import {api,errorText} from '@/components/plant/plantUtils';
import {toast} from '@/components/ui/use-toast';
export default function WorkspaceSettings({workspace,onSaved}) {
  const [name,setName]=useState(workspace.name),[appName,setAppName]=useState(workspace.app_name||'LPDSI Limay 1'),[clockFormat,setClockFormat]=useState(workspace.clock_format||'12'),[plant,setPlant]=useState(workspace.plant||''),[members,setMembers]=useState(workspace.member_emails||[]),[email,setEmail]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false);
  const [clearStep,setClearStep]=useState(0),[clearBusy,setClearBusy]=useState(false),[clearText,setClearText]=useState('');
  const save=async e=>{e.preventDefault();setBusy(true);setSaved(false);try{await api('settings',{workspace_id:workspace.id,data:{name,app_name:appName,clock_format:clockFormat,plant,member_emails:members,designation:workspace.designation,plant_role:workspace.plant_role,shift:workspace.shift}});await onSaved();setSaved(true);toast({title:'Workspace settings saved'});}catch(e){toast({title:'Settings update failed',description:errorText(e),variant:'destructive'});}finally{setBusy(false);}};
  const add=()=>{if(!/^\S+@\S+\.\S+$/.test(email)){toast({title:'Enter a valid email address',variant:'destructive'});return;}setMembers([...new Set([...members,email.toLowerCase().trim()])]);setEmail('');setSaved(false);};
  const clearData=async()=>{setClearBusy(true);try{await api('clearData',{workspace_id:workspace.id});setClearStep(0);setClearText('');await onSaved();toast({title:'Workspace data cleared'});}catch(e){toast({title:'Could not clear workspace data',description:errorText(e),variant:'destructive'});}finally{setClearBusy(false);}};
  const confirmInput=<input value={clearText} onChange={e=>setClearText(e.target.value)} placeholder={workspace.name} style={{width:'100%',background:'var(--surface-2)',border:'1px solid var(--line)',borderRadius:7,padding:'8px 10px',marginBottom:10,color:'var(--ink)',outline:'none'}}/>;
  return <form className="settings-layout" onSubmit={save}>
    <section className="panel settings-panel"><h3><Building2 size={18}/>Workspace details</h3><p>Your dedicated instrumentation and control workspace.</p><label className="form-field">App header name<input required maxLength={80} value={appName} onChange={e=>{setAppName(e.target.value);setSaved(false);}}/></label><label className="form-field">Workspace name<input required value={name} onChange={e=>{setName(e.target.value);setSaved(false);}}/></label><label className="form-field">Plant / site name<input value={plant} onChange={e=>{setPlant(e.target.value);setSaved(false);}}/></label><fieldset className="clock-format-setting"><legend>Real-time clock format</legend><label><input type="radio" name="clock-format" value="12" checked={clockFormat==='12'} onChange={()=>{setClockFormat('12');setSaved(false);}}/>12-hour <span>AM/PM</span></label><label><input type="radio" name="clock-format" value="24" checked={clockFormat==='24'} onChange={()=>{setClockFormat('24');setSaved(false);}}/>24-hour</label></fieldset><div className="settings-isolation"><ShieldCheck size={21}/><div><strong>Workspace data isolation is enabled</strong><p>Only you and field users you authorize can access this workspace. Other supervisors cannot see your plant records.</p></div></div></section>
    <section className="panel settings-panel"><h3><Users size={18}/>Field user access</h3><p>Grant access by email. Members register using that email, then select your workspace. This does not send an invitation.</p><div className="member-input"><input type="email" aria-label="Field user email" placeholder="technician@company.com" value={email} onChange={e=>setEmail(e.target.value)}/><button type="button" className="secondary-button" onClick={add}><Plus size={15}/>Add</button></div><div className="member-list">{members.length?members.map(m=><div key={m}><span>{m}</span><small>FIELD USER</small><button type="button" className="icon-button" aria-label={`Remove ${m}`} onClick={()=>{setMembers(members.filter(x=>x!==m));setSaved(false);}}><X size={14}/></button></div>):<p>No field users have been added.</p>}</div><div className="role-note"><strong>Field user permissions</strong><p>Update execution logs, materials and work status. Create, edit and delete break-in records. Imports, analytics, scheduled job information and settings remain supervisor-only.</p></div></section>
    <div className="settings-save">{saved&&<span className="saved-label"><Check size={15}/>Workspace settings saved</span>}<button className="primary-button" disabled={busy}><Save size={16}/>{busy?'Saving…':'Save workspace settings'}</button></div>
    <section className="danger-zone"><h3><AlertTriangle size={18}/>Danger Zone</h3><p>Permanently delete all work orders in this workspace. This action cannot be undone. Use this if an import corrupts your data and you need a clean slate.</p>
      {clearStep===0&&<button type="button" onClick={()=>setClearStep(1)}><Trash2 size={16}/>Clear all workspace data</button>}
      {clearStep===1&&<div><p style={{color:'var(--red)',fontWeight:600,marginBottom:10}}>Are you absolutely sure? This will delete ALL work orders in {workspace.name}.</p><div style={{display:'flex',gap:8}}><button type="button" onClick={()=>setClearStep(2)}>Yes, proceed</button><button type="button" className="secondary-button" onClick={()=>setClearStep(0)}>Cancel</button></div></div>}
      {clearStep===2&&<div><p style={{color:'var(--red)',fontWeight:700,marginBottom:10}}>Type the workspace name to confirm: <strong>{workspace.name}</strong></p>{confirmInput}<div style={{display:'flex',gap:8}}><button type="button" onClick={clearData} disabled={clearBusy||clearText!==workspace.name}>{clearBusy?<Loader2 size={16} className="animate-spin"/>:<Trash2 size={16}/>}Permanently delete all data</button><button type="button" className="secondary-button" onClick={()=>{setClearStep(0);setClearText('');}} disabled={clearBusy}>Cancel</button></div></div>}
    </section>
  </form>;
}